events/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
]

inkchallenger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('main_app.urls', 'main_app'), namespace='main_app')),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
    path('admin/', admin.site.urls),
]

events/forms.py
from django.forms import ModelForm
from .models import *

class FeedingForm(ModelForm):
  class Meta:
    model = Event
    fields = ['day', 'start_time', 'notes']

events/templates/base1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>The Ink Challenger</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Amatic+SC|Amiri|Playfair+Display+SC"
        rel="stylesheet">

</head>

<body class="home">
    <header>
        <a class="logo-home" href="{% url 'main_app:home' %}">Home</a>
        </div>
        <input class="menu-ham" type="checkbox" id="menu-ham" />
        <label class="menu-icon" for="menu-ham"><span class="navicon"></span></label>
            <ul class="menu">
                </ul>
              
    </header>
    <br>
    <br>
    <br>
    <br>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <div><a class="left" href="#">Contact PRV</a></div>
        <div><a class="right" href="#">All Rights Reserved &copy; 2019 PRV Ink &copy; The Ink Challenger</a></div>
    </footer>

</body>

</html>

events/templates/event_form.html
{% extends 'base.html' %}

{% block content %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

events/templates/home1.html
{% extends 'base1.html' %}
{% block content %}

<h1>WE CAN LINK APPS NOW</h1>
<h1> {{ context }}</h1>

{% endblock %}